version: '3.1'

services:

  db:
    image: postgres:12.11-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./backups:/var/lib/postgresql/backups
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080